# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: On Push

on:
  push:
    branches:
      - '*'

jobs:
  generate-source:
    name: Generate Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: Clobber
        run: make -C auto clobber
      - name: Generate Extensions
        run: make -C auto
      - name: Upload Generated Source Code
        uses: actions/upload-artifact@v7
        with:
          name: generated-source
          path: |
            include/GL
            src
            doc
            build
      # Look into this:
      # https://github.com/marketplace/actions/cache-apt-packages
      - name: Install Dependencies
        run: sudo apt install -y dos2unix
      - name: Generate Distributable Source
        run: make dist-src
      - name: Upload Distributable Source
        uses: actions/upload-artifact@v7
        with:
          name: distributable-source-archives
          path: |
            glew-*.zip
            glew-*.tgz
  compile-clang:
    name: Ubuntu Linux Build
    needs:
      - generate-source
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        system:
          - linux
          - linux-egl
          - linux-clang
          - linux-clang-egl
          - linux-mingw32
          - linux-mingw64
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: Download Generated Source Code
        uses: actions/download-artifact@v8
        with:
          name: generated-source
      - name: Install Dependencies
        run: sudo apt install -y clang mingw-w64 libxmu-dev libxi-dev libgl-dev libegl1-mesa-dev dos2unix
      - name: Clean
        run: make clean
      - name: Build Binaries
        env:
          SYSTEM: ${{ matrix.system }}
        run: make
      - name: Upload Binaries
        uses: actions/upload-artifact@v7
        with:
          name: binaries-${{ matrix.system }}
          path: |
            bin/
            lib/
  compile-cmake:
    name: Ubuntu Linux CMake Build
    needs:
      - generate-source
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Debug
          - Release
        shared-lib:
          - false
          - true
        egl:
          - false
          - true
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: Download Generated Source Code
        uses: actions/download-artifact@v8
        with:
          name: generated-source
      - name: Install Dependencies
        run: sudo apt install -y cmake ninja-build libxmu-dev libxi-dev libgl-dev libegl1-mesa-dev dos2unix
      # Look into this:
      # https://github.com/threeal/cmake-action
      # https://github.com/threeal/ctest-action
      - name: Make Build Directory
        run: mkdir build_
      - name: CMake
        run: >-
          cmake build/cmake
          -B build_
          -G Ninja
          --fresh
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
          -DGLEW_X11=${{ case(matrix.egl, 'N', 'Y') }}
          -DGLEW_EGL=${{ case(matrix.egl, 'Y', 'N') }}
          -DBUILD_SHARED_LIBS=${{ case(matrix.shared-lib, 'Y', 'N') }}
           --verbose
      - name: CMake Build
        run: cmake --build build_ --verbose
      - name: Clean Up
        run: rm -Rf build_
      - name: Upload Binaries
        uses: actions/upload-artifact@v7
        with:
          name: binaries-${{ matrix.build-type }}-${{ case(matrix.egl, 'egl', 'x11') }}-${{ case(matrix.shared-lib, 'shared', 'static') }}
          path: |
            bin/
            lib/
