# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: On Push

on:
  push:
    branches:
      - '*'

jobs:
  cache-debian-packages:
    name: Cache Debian Packages
    runs-on: ubuntu-latest
    steps:
      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          key: dpkgs
          path: ~/.dpkg/
      - name: Update
        run: sudo apt-get update
      - name: Install Dependencies
        run: >-
          sudo apt-get install
          -o dir::cache::archives=~/.dpkg/
          -y
          clang
          cmake
          mingw-w64
          ninja-build
          libxmu-dev
          libxi-dev
          libgl-dev
          libegl1-mesa-dev
          dos2unix
  generate-source:
    name: Generate Source Code
    needs:
      - cache-debian-packages
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: Fetch Cached Dependencies
        uses: actions/cache/restore@v5
        with:
          key: dpkgs
          path: ~/.dpkg/
      - name: Clobber
        run: make -C auto clobber
      - name: Generate Extensions
        run: make -C auto
      - name: Upload Generated Source Code
        uses: actions/upload-artifact@v7
        with:
          name: generated-source
          path: |
            include/GL
            src
            doc
            build
      # Look into this:
      # https://github.com/marketplace/actions/cache-apt-packages
      - name: Update
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get install -o dir::cache::archives=~/.dpkg/ -y dos2unix
      - name: Generate Distributable Source
        run: make dist-src
      - name: Upload Distributable Source
        uses: actions/upload-artifact@v7
        with:
          name: distributable-source-archives
          path: |
            glew-*.zip
            glew-*.tgz
  makefile-build:
    name: Makefile
    needs:
      - cache-debian-packages
      - generate-source
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        system:
          - linux
          - linux-egl
          - linux-clang
          - linux-clang-egl
          - linux-mingw32
          - linux-mingw64
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: Fetch Cached Dependencies
        uses: actions/cache/restore@v5
        with:
          key: dpkgs
          path: ~/.dpkg/
      - name: Download Generated Source Code
        uses: actions/download-artifact@v8
        with:
          name: generated-source
      - name: Update
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get install -o dir::cache::archives=~/.dpkg/ -y clang mingw-w64 libxmu-dev libxi-dev libgl-dev libegl1-mesa-dev dos2unix
      - name: Clean
        run: make clean
      - name: Make
        env:
          SYSTEM: ${{ matrix.system }}
        run: make
      - name: Upload Binaries
        uses: actions/upload-artifact@v7
        with:
          name: binaries-${{ matrix.system }}
          path: |
            bin/
            lib/
  cmake-build:
    name: CMake
    needs:
      - cache-debian-packages
      - generate-source
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Debug
          - Release
        shared-lib:
          - false
          - true
        egl:
          - false
          - true
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: Fetch Cached Dependencies
        uses: actions/cache/restore@v5
        with:
          key: dpkgs
          path: ~/.dpkg/
      - name: Download Generated Source Code
        uses: actions/download-artifact@v8
        with:
          name: generated-source
      - name: Update
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get install -o dir::cache::archives=~/.dpkg/ -y cmake ninja-build libxmu-dev libxi-dev libgl-dev libegl1-mesa-dev dos2unix
      # Look into this:
      # https://github.com/threeal/cmake-action
      # https://github.com/threeal/ctest-action
      - name: Make Build Directory
        run: mkdir build_
      - name: CMake
        run: >-
          cmake build/cmake
          -B build_
          -G Ninja
          --fresh
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
          -DGLEW_X11=${{ case(matrix.egl, 'N', 'Y') }}
          -DGLEW_EGL=${{ case(matrix.egl, 'Y', 'N') }}
          -DBUILD_SHARED_LIBS=${{ case(matrix.shared-lib, 'Y', 'N') }}
      - name: CMake Build
        run: cmake --build build_
      - name: Make Install Directory
        run: mkdir install
      - name: CMake Install
        run: cmake --install build_ --prefix install
      - name: Upload Binaries
        uses: actions/upload-artifact@v7
        with:
          name: binaries-${{ matrix.build-type }}-${{ case(matrix.egl, 'egl', 'x11') }}-${{ case(matrix.shared-lib, 'shared', 'static') }}
          path: install/*
  nuget-package:
    name: NuGet
    needs:
      - makefile-build
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: Download Generated Source Code
        uses: actions/download-artifact@v8
        with:
          name: generated-source
      - name: Download Binaries (x86)
        uses: actions/download-artifact@v8
        with:
          name: binaries-linux-mingw32
          path: x86
      - name: Download Binaries (x64)
        uses: actions/download-artifact@v8
        with:
          name: binaries-linux-mingw64
          path: x64
      - id: get-version
        name: Get Version
        shell: bash
        run: cat config/version | sed 's/ //g;s/(/{/g;s/)/}/g' >> "$GITHUB_OUTPUT"
      - name: Rename
        shell: bash
        run: |
          mv x86/lib/libglew32.dll.a x86/lib/glew32.lib
          mv x64/lib/libglew32.dll.a x64/lib/glew32.lib
      - name: NuGet Pack (DLL)
        run: >-
          nuget pack nuget/glew.dynamic.nuspec
          -BasePath .
          -NonInteractive
          -Verbosity detailed
          -Properties Version=${{ steps.get-version.outputs.GLEW_VERSION }};Configuration=Release
      - name: Rename
        shell: bash
        run: |
          mv x86/lib/libglew32.a x86/lib/glew32.lib
          mv x64/lib/libglew32.a x64/lib/glew32.lib
      - name: NuGet Pack (static)
        run: >-
          nuget pack nuget/glew.static.nuspec
          -BasePath .
          -NonInteractive
          -Verbosity detailed
          -Properties Version=${{ steps.get-version.outputs.GLEW_VERSION }};Configuration=Release
      - name: Upload Packages
        uses: actions/upload-artifact@v7
        with:
          name: nuget
          path: '**/*.nupkg'
